name: Release Docker Images

on:
  push:
  branches:
      - rc/*
    tags:
      - v3.*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.4

    - name: Build Docker Image
      run: |
        docker buildx build \
          --tag growi
          --platform linux/amd64 \
          --output "type=image,push=false" \
          --file ./docker/Dockerfile .

    - name: Login to docker.io registry
      run: |
        docker login --username wsmoogle --password ${{ secrets. DOCKER_REGISTRY_PASSWORD }}

    - name: Publish
      run: |
        docker tag growi weseek/growi:latest
        docker publish weseek/growi:latest

  build-nocdn:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.4

    - name: Build Docker Image
      run: |
        docker buildx build \
          --tag growi-nocdn
          --build-arg flavor=nocdn
          --platform linux/amd64 \
          --output "type=image,push=false" \
          --file ./docker/Dockerfile .

  publish-desc:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v1

    - name: Bump version
      run: sh ./bin/github-actions/bump-version.sh
