name: Release Docker Images for RC

on:
  push:
    branches:
      - rc/*

jobs:

  build-rc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.4

    - name: Build Docker Image
      run: |
        docker buildx build \
          --tag growi
          --platform linux/amd64 \
          --output "type=image,push=false" \
          --file ./docker/Dockerfile .

    - name: Login to docker.io registry
      run: |
        docker login --username wsmoogle --password ${{ secrets. DOCKER_REGISTRY_PASSWORD }}

    - name: Publish
      run: |
        docker tag growi weseek/growi:latest
        docker publish weseek/growi:latest
