name: Release Docker Images (NOCDN)

on:
  push:
    tags:
      - v3.*

jobs:

  build-rc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.4

    - name: Login to docker.io registry
      run: |
        echo ${{ secrets. DOCKER_REGISTRY_PASSWORD }} | docker login --username wsmoogle --password-stdin

    - name: Build Docker Image
      run: |
        CACHE_REF=weseek/growi-cache:3-nocdn
        docker buildx build \
          --tag growi \
          --platform linux/amd64 \
          --load \
          --cache-from=type=registry,ref=$CACHE_REF \
          --cache-to=type=registry,ref=$CACHE_REF,mode=max \
          --file ./docker/Dockerfile .

    - name: Get SemVer
      run: |
        semver=`npm run version --silent`
        echo ::set-env name=SEMVER::$(echo $semver)

    - name: Docker Tags by SemVer
      uses: weseek/ghaction-docker-tags-by-semver@v1.0.3
      with:
        source: growi
        target: weseek/growi
        semver: ${{ env.SEMVER }}
        suffix: -nocdn
        publish: true

  publish-desc:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v1

    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: wsmoogle
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        DOCKERHUB_REPOSITORY: weseek/growi
        README_FILEPATH: ./docker/README.md
