name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Bump version
      run: sh ./bin/bump-version.sh
      
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.4
      with:
        # Buildx version. Example: v0.3.0
        version: # optional, default is latest

    - name: Build Docker Image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --output "type=image,push=false" \
          --file ./docker/Dockerfile ./docker
